apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-api
  namespace: hello-api
  annotations:
    iam.gke.io/gcp-service-account: hello-api-gsa@project-ba3c3f08-4f71-4bf4-b3c.iam.gserviceaccount.com
